export enum NewsEnum {
  COMPANY = "COMPANY",
  INSURANCE = "INSURANCE",
  SHAREHOLDER = "SHAREHOLDER",
  ARTICLE = "ARTICLE",
  LEARNING = "LEARNING",
  SHARE = "SHARE",
  FINANCE = "FINANCE",
  INVITATIONS = "INVITATIONS",
  CONSTITUENT = "CONSTITUENT",
  GENERAL = "GENERAL",
}
